### ISSUE TITLE
IDA plugin error

### ISSUE THREAD

**Issue by DairyStix** [cseagle/collabREate#3]
When launching IDA 7.1 after copying the collabreate64.dll to the IDA plugin directory I get the error "Fatal error before kernel init". 32 Bit works fine. Any ideas what could be the issue? 

Thanks in advance.

**Comment by cseagle** [comment]
What platform are you running IDA on? I assume Windows? I am not seeing this behavior, but I have been working from a local copy of IDA for which I committed changes last night. I will test on Linux and Mac as well to see if I can reproduce there.

**Comment by DairyStix** [comment]
Yes apologies, Windows 10. 

Thank you.

**Comment by DairyStix** [comment]
Just looked at this again and I've solved it. My visual studio was using the wrong architecture for the linker option. All sorted now.

Thanks!
